ARG UBUNTU_DIST=noble
FROM ubuntu:noble

ARG UBUNTU_DIST
ARG VERSION
ARG BUILD_VERSION
ARG FULL_VERSION
ARG ARCH
ARG TERMUSIC_RELEASE

RUN mkdir -p /output/usr/bin
RUN mkdir -p /output/usr/share/doc/termusic
RUN mkdir -p /output/DEBIAN

COPY ${TERMUSIC_RELEASE}/termusic /output/usr/bin/
COPY ${TERMUSIC_RELEASE}/termusic-server /output/usr/bin/
COPY output/DEBIAN/control /output/DEBIAN/
COPY output/DEBIAN/postinst /output/DEBIAN/postinst
RUN chmod 755 /output/DEBIAN/postinst
COPY output/copyright /output/usr/share/doc/termusic/
COPY output/changelog.Debian /output/usr/share/doc/termusic/
COPY output/README.md /output/usr/share/doc/termusic/

RUN chmod 755 /output/usr/bin/termusic /output/usr/bin/termusic-server

RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/usr/share/doc/termusic/changelog.Debian
RUN sed -i "s/FULL_VERSION/$FULL_VERSION/" /output/usr/share/doc/termusic/changelog.Debian
RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/DEBIAN/control
RUN sed -i "s/VERSION/$VERSION/" /output/DEBIAN/control
RUN sed -i "s/BUILD_VERSION/$BUILD_VERSION/" /output/DEBIAN/control
RUN sed -i "s/SUPPORTED_ARCHITECTURES/$ARCH/" /output/DEBIAN/control

RUN dpkg-deb --build /output /termusic_${FULL_VERSION}.deb
