name: Build termusic for Debian

on:
  workflow_dispatch:
    inputs:
      termusic_version:
        description: The version of termusic to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true

permissions:
  contents: write

jobs:
  build-termusic:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout termusic-debian
        uses: actions/checkout@v4

      - name: Build termusic
        run: ./build.sh ${{ inputs.termusic_version }} ${{ inputs.build_version }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: termusic_*.deb


  release-termusic:
    name: (Draft-)Release termusic for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-termusic
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: termusic_*.deb
          name: ${{ inputs.termusic_version }}+${{ inputs.build_version }}
          tag_name: ${{ env.RELEASE_TAG }}
          fail_on_unmatched_files: true
